In [2]:
import numpy as np
import scipy as sp

In [3]:
from quadrotor.dynamics import QuadrotorDynamicsBase, QuadrotorState
from quadrotor.controller import ControllerBase, QuadrotorCommands
from quadrotor.trajectory import TrajectoryBase, TrajectoryState

In [4]:
from sym import Rot3

def dRot3(R: Rot3, omega: np.ndarray) -> Rot3:
    """
    NOTE(roy): If interested, we can discuss the math here later. There are other
    ways of doing this but to keep the ode_int formulation, we specifically require
    dq/dt. Refer to 'Baseile Graf - Quaternions and Dynamics' or (for intuition)
    https://math.stackexchange.com/questions/1896379/how-to-use-the-quaternion-derivative
    """
    quat = np.array(R.to_storage())  # Convert to raw quaternion
    (q0, q1, q2, q3) = quat  # xyzw storage, see https://symforce.org/api-gen-cpp/class/classsym_1_1Rot3.html

    G = np.array([[ q3,  q2, -q1, -q0],
                [-q2,  q3,  q0, -q1],
                [ q1, -q0,  q3, -q2]])
    quat_dot = (G.T @ omega) / 2
    return Rot3.from_storage(quat_dot)

### Building a 3D quadrotor model
In this second notebook, we'll build a full 3-dimensional quadrotor model! In this one I will be leaving you guys alone a lot more, but as discussed in the lectures, there is a lot of overlap with the 2D model we made last week, so feel free to copy your implementation from there and simply expand it here!

**When implementing things like this, I recommend working in steps!** For example, in your 2D model, you may find it's much better to _first_ model the accelerations; see whether that works and only _then_ move on to the angular acceleration. If you do both at the same time, finding bugs (and everyone introduces bugs once in a while!) is much harder. **Keep testing as you write code!**

#### Recommended steps
- Copy your 2D quadrotor model
- Work your way down the same way we did on the 3D model
    - Implement the mixing matrix (i.e. compute u1 and u2 from the rotor rates)
    - Modify the `state_derivative` functions to take a vector for u2 rather than a float (because now of course that's 3 numbers!)
    - Modify the `accel` formulation in your model to 3D (see equations in slides)
    - Modify the `angular_accel` formulation in your model to 3D (see equations in slides)

In [5]:
from dataclasses import dataclass, field

@dataclass
class Params:
    """A little utility class to hold our quadrotor parameters"""
    mass: float = 1.352  # [kg]

    # NOTE(roy) this is a matrix now as discussed!
    # NOTE(roy) don't get scared by the field/default_factory thing! It's just a way to do default field initialization for dataclasses,
    # see https://docs.python.org/3/library/dataclasses.html. Don't worry about it!
    inertia: np.ndarray = field(default_factory=lambda: np.array([
        [9.8e-3, 0, 0],
        [0, 10.02e-3, 0],
        [0, 0, 18.6e-3],
    ]))

    rotor_diameter: float = 10 * 0.0254  # [m] 10 inches

    static_thrust_coefficient: float = 0.14553  # [-] Thrust coefficient
    static_torque_coefficient: float = 0.01047  # [-] Torque coefficient

    # NOTE(roy) assume this is the same front-to-back and left-to-right
    arm_length: float = 0.3814 / 2.0  # [m] Arm length

    # Universal constants
    g: float = 9.80665  # [m/s2] Gravity
    rho: float = 1.225  # [kg/m3] Sea-level density

    def rotor_model(self, static_coefficient: float) -> float:
        # NOTE(roy) I'm just including this for completeness sake, this means we can e.g. see how air density
        # influences our simulation
        # Refer to this source for derivation: https://web.mit.edu/16.unified/www/FALL/thermodynamics/notes/node86.html
        return self.rho * static_coefficient * (self.rotor_diameter ** 4) / (4 * np.pi ** 2)

    # NOTE(roy) if you're unsure what @property decorators do: they make it so that we can call k_thrust as if it was just a class
    # variable. I.e. we'd write params.k_thrust now, rather than params.k_thrust()
    @property
    def k_thrust(self):
        return self.rotor_model(self.static_thrust_coefficient)
        # this represents the upward thrust coefficient, will be multiplied by the speed of the rotor squared, to get upward force
        # in Project Session 3 slide 23, this is F = kT * ω^2

    @property
    def k_torque(self):
        return self.rotor_model(self.static_torque_coefficient)
        # this represents the torque coefficient, will be multiplied by the speed of the rotor squared to get moment at each rotor
        # in Project Session 3 slide 23, this is M = kM * ω^2

# Simply treat as a global
p = Params()

In [47]:
class FullQuadrotorDynamics(QuadrotorDynamicsBase):
    def __init__(self) -> None:
        # NOTE(roy): I advise you to scroll through dynamics.py and see what the __init__
        # function in the base class does!
        super().__init__()

    @staticmethod
    def rotor_thrust_model(rotor_rates: np.ndarray) -> np.ndarray:
        # NOTE(roy): Implement the simple rotor trust model we discussed in the slides
        # To see how complex this can get, see for example: https://arxiv.org/pdf/1601.00733.pdf
        # force of each rotor is related to rotor rates squared times constant p.k_thrust
        forces =  rotor_rates * rotor_rates * p.k_thrust     
        return forces

    def step(self, t: float, input: QuadrotorCommands) -> QuadrotorState:
        # Like I said; copy over your 2D model as a great starting point,
        # we just need to update the control inputs (u) and the accel/angular_accel formulations in the state_derivative function.
        # (Also give it a better name of course!)
        # Note that in numpy, the * operator will do an element-wise operation and @ will do matrix multiplication!
        # (e.g. A * x != A @ x , try it for yourself in a separate cell!)
        # Try to use matrices/vectors where you can! For example,
        # I recommend that you write the mixing matrix as an actual mixing matrix like it’s given in the slides
        # and multiply it with the rotor thrust vector (rather than doing a for loop or something like that)!
        # This means you can write something like u = mixing_matrix @ forces

        # NOTE(roy) Use only the first two rotor rates (for 2d version)
        F1, F2, F3, F4 = FullQuadrotorDynamics.rotor_thrust_model(input.rotor_rates)

        # NOTE(roy) Implement the thrust/torque calculation we discussed in the slides
        km_over_kt = p.k_torque / p.k_thrust
        mixing_matrix = np.array([
            [1,                     1,                      1,                  1],
            [0,                     p.arm_length,           0,                  -1 * p.arm_length],
            [-1 * p.arm_length,     0,                      p.arm_length,       0],
            [km_over_kt,            -1 * km_over_kt,        km_over_kt,         -1 * km_over_kt]
        ])


        u = mixing_matrix @ np.array([
                                    [F1],
                                    [F2],
                                    [F3],
                                    [F4]])
        # print("u =", u)
        # u will be a vertical matrix that is 4 high (up force, MomentX, MomentY, MomentZ) like this:
        #                                   [[ 9.74380852e+00]
        #                                    [-1.45836655e-17]
        #                                    [ 1.45836655e-17]
        #                                    [ 0.00000000e+00]]


        u1 = u[0][0]
        # print("u1 =", u1)
        #                                   resulting u1 will be just a number such as 9.743808515905304


        u2 = u[1:4]
        # print("u2 =", u2)
        #                                   resulting u2 will be 3 high matrix, something like:
        #                                   [[-1.45836655e-17]
        #                                    [ 1.45836655e-17]
        #                                    [ 0.00000000e+00]]


        # NOTE(roy) this local function is a wrapper around the class state_derivative function
        # all this does is convert the our state dataclass from/into a vector that the scipy
        # integration solver can work with. See dynamics.py for the definition of these
        # from/to state vector functions.
        def state_derivative(t: float, state: np.ndarray) -> np.ndarray:
            return FullQuadrotorDynamics.state_derivative(
                t,
                QuadrotorState.from_state_vector(state),
                u1,
                u2
            ).to_state_vector()

        state_vector = self.state.to_state_vector()

        # read about this function here: https://docs.scipy.org/doc/scipy/reference/generated/scipy.integrate.solve_ivp.html
        solution = sp.integrate.solve_ivp(state_derivative, (0, self.dt), state_vector)

        self.state = QuadrotorState.from_state_vector(solution['y'][:, -1])
        return self.state
    
    # find out what a static method is, and what the decorator does! here's one google result: 
    # https://stackoverflow.com/questions/136097/what-is-the-difference-between-staticmethod-and-classmethod-in-python
    
    @staticmethod
    def state_derivative(t: float, state: QuadrotorState, u1: np.ndarray, u2:np.ndarray) -> QuadrotorState:

        Rab = state.orientation
        # print("r = state.orientation =", r)
        #                                   Rab will be a Rot3 such as <Rot3 [-5.856823395437519e-17, 5.856823395437519e-17, 1.6466933414892838e-51, 1.0]>

        accel = (np.array([0, 0, -  p.g]) + Rab * np.array([0, 0, u1])) / p.mass # this is taking the "upward" force and rotating it by the state.orientation and dividing by mass

        # angular_accel = Rab * u2  # this is taking the torques (x, y, z) and rotating them by the state.orientation
        # print("angular_accel that does not crash =", angular_accel)

        # https://numpy.org/doc/stable/reference/generated/numpy.cross.html
        # numpy.cross(a, b, axisa=-1, axisb=-1, axisc=-1, axis=None)[source]            (Return the cross product of two (arrays of) vectors.)

        M = Rab * u2  # this is taking the torques (x, y, z) and rotating them by the state.orientation


        # print("state.angular_velocity =",state.angular_velocity)
        # print("np.cross(state.angular_velocity, p.inertia) =", np.cross(state.angular_velocity, p.inertia))
        # print("(M - np.cross(state.angular_velocity, p.inertia) * state.angular_velocity) =", (M - np.cross(state.angular_velocity, p.inertia) * state.angular_velocity))
        # print("np.linalg.inv(p.inertia) =", np.linalg.inv(p.inertia))

        angular_accel = np.linalg.inv(p.inertia) @ (M - np.cross(state.angular_velocity, p.inertia) * state.angular_velocity)

        print("angular_accel =", angular_accel)

        #                                   this should be a 3 high matrix, such as:
        #                                   [[-1.45836655e-17]
        #                                    [ 1.45836655e-17]
        #                                    [ 0.00000000e+00]]


        angular_accel = angular_accel.reshape(-1)
        # print("angular_accel = angular_accel.reshape(-1) =", angular_accel)
        #                                   this converts it into a vector such as = [-1.45836655e-17  1.45836655e-17  0.00000000e+00]









        # NOTE(roy) this might look a little confusing at first glance, but we're populating DERIVATIVES
        # of the state here! So position -> velocity, velocity -> acceleration, etc...
        # If you can think of a more readable way to do this (e.g. defining a QuadrotorStateDerivative class)
        # feel free to open a pull-request into the upstream repository!
        state_derivative = QuadrotorState(
            position=state.velocity,
            velocity=accel,
            orientation=dRot3(state.orientation, state.angular_velocity),
            angular_velocity= angular_accel
        )

        return state_derivative

This code is largely the same, I set the rotor rates to 300 rad/s now, you should see it be very close to hovering with these numbers! (As I hope you found in the previous assignment as well with 600rad/s!)

In [48]:
class EmptyTrajectory(TrajectoryBase):
    def eval(self, *args):
        return TrajectoryState(0.0, position=np.zeros(3))  # Trajectory not yet important

class EmptyController(ControllerBase):
    def step(self, *args) -> QuadrotorCommands:
        return QuadrotorCommands(np.array([360, 360, 360, 360]))

In [49]:
from quadrotor.simulator import SimulatorBase, SimulatorState

# This might be slow to run the first time!
from quadrotor.renderer import animate_k3d, animate_matplotlib

In [50]:
def run_and_render(initial_state: QuadrotorState, t_total: int = 0.5):
    sim = SimulatorBase(
        dt=0.01,
        dynamics=FullQuadrotorDynamics(),
        controller=EmptyController(),
        trajectory=EmptyTrajectory(),
        initial_state=initial_state,
        t_total=t_total,
    )
    
    # Run the simulator
    output = sim.simulate()

    # K3D renderer
    plot = animate_k3d(output)
    
    plot.display()
    plot.start_auto_play()
    # print(output)
    
    # state.orientation.to_yaw_pitch_roll()

In [51]:
# NOTE(roy) play with this variable and see what happens!
initial_state = QuadrotorState(
    position=np.zeros(3),
    velocity=np.array([0, 0, 0]),
    orientation=Rot3.from_yaw_pitch_roll(0, 0, 0),
    angular_velocity=np.zeros(3),
)

run_and_render(initial_state, 4)

angular_accel = [[-1.48812913e-15 -1.48812913e-15 -1.48812913e-15]
 [ 1.45545564e-15  1.45545564e-15  1.45545564e-15]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00]]


ValueError: operands could not be broadcast together with shapes (19,) (13,) 

### Does the simulated model make any sense?
If all is well, you should see the quadrotor roughly hovering with those 600 rad/s rotor rates

Now try some experiments for yourself and describe whether the behavior is as expected or whether there is anything wrong with your model, ideas to try:
- Can you make the vehicle yaw by setting a combination of rotor rates?
- Can you make the vehicle move forward/backward left/right by correctly lowering two rotor rates each time?
- What happens if you're in hover (i.e. the 600rad/s) and disable one rotor?

### Commit your updated notebook to your fork!